mlflow:
  experiment: "SimpleRoad"
  url: "http://10.56.238.20:9999"
  user: "Local"
hyper_parameters:
  hiddens: [ 256, 256, 128, 128 ]
  framework: torch
  double_q: true
  dueling: true
  noisy: false
  adam_epsilon: .00015
  exploration_config:
    epsilon_timesteps: 500000
    final_epsilon: 0.01
  lr: 0.0001
  n_step: 5
  num_atoms: 1
  replay_buffer_config:
    capacity: 1000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1
    type: MultiAgentPrioritizedReplayBuffer
  num_gpus: 1
  num_cpus_per_worker: 1
  num_gpus_per_worker: 0
  num_envs_per_worker: 4
  num_workers: 18
  num_steps_sampled_before_learning_starts: 20000
  rollout_fragment_length: 32
  target_network_update_freq: 50000
  train_batch_size: 1024
  min_sample_timesteps_per_iteration: 20000
  always_attach_evaluation_results: True
log:
  save_file: "/home/seventheli/data/logging/simple_env"
  save_checkout: "/home/seventheli/data/checkpoints/simple_env"
  max_time: 360000
  log: 1
