name: drone
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - python=3.9
  - opencv
  - pip:
      - Farama-Notifications==0.0.4
      - absl-py==1.4.0
      - aiohttp-cors==0.7.0
      - aiohttp==3.9.0
      - aiorwlock==1.3.0
      - aiosignal==1.3.1
      - alembic==1.13.0
      - anyio==3.7.1
      - arrow==1.2.2
      - asgiref==3.5.2
      - async-timeout==4.0.3
      - backoff==2.2.1
      - blessed==1.20.0
      - blinker==1.7.0
      - boto3==1.23.10
      - botocore==1.26.10
      - cachetools==5.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - boto3==1.23.10
      - click==8.1.7
      - cloudpickle==2.2.1
      - coloredlogs==15.0.1
      - colorful==0.5.4
      - contourpy==1.0.6
      - cycler==0.11.0
      - databricks-cli==0.18.0
      - debugpy==1.8.0
      - deprecated==1.2.14
      - distlib==0.3.6
      - distro==1.7.0
      - dm-tree==0.1.7
      - docker==6.1.3
      - dynaconf==3.1.9
      - exceptiongroup==1.1.3
      - farama-notifications==0.0.4
      - fastapi==0.104.1
      - filelock==3.13.1
      - flask==3.0.0
      - flatbuffers==23.5.26
      - fonttools==4.37.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - func-timeout==4.3.5
      - google-api-core==2.10.2
      - google-auth==2.16.1
      - googleapis-common-protos==1.57.0
      - gpustat==1.1.1
      - gputil==1.4.0
      - greenlet==3.0.1
      - grpcio==1.43.0
      - gunicorn==21.2.0
      - gutils==0.1.9
      - gymnasium==0.28.1
      - h11==0.13.0
      - httptools==0.3.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.25.1
      - importlib-metadata==6.8.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpointer==2.3
      - jsonschema-specifications==2023.11.1
      - jupyter-client==8.6.0
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - libtorrent==2.0.7
      - llvmlite==0.39.0
      - lz4==4.0.2
      - mako==1.3.0
      - markdown-it-py==3.0.0
      - markdown==3.4.1
      - markupsafe==2.1.3
      - matplotlib==3.7.0
      - mdurl==0.1.2
      - minigrid==2.3.1
      - mlflow==2.8.1
      - mpmath==1.3.0
      - mpu==0.23.1
      - msgpack==1.0.4
      - multidict==6.0.4
      - networkx==2.8.8
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - onnx==1.15.0
      - onnxruntime==1.17.0
      - opencensus-context==0.1.3
      - opencensus==0.11.0
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-grpc==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-exporter-otlp==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - packaging==21.3
      - pandas==2.1.3
      - pillow==9.3.0
      - platformdirs==3.11.0
      - prometheus-client==0.13.0
      - protobuf==3.20.3
      - psutil==5.9.6
      - py-spy==0.3.12
      - pyarrow==6.0.1
      - pyasn1-modules==0.2.8
      - pyasn1==0.4.8
      - pydantic==1.10.13
      - pygame==2.5.2
      - pygments==2.17.1
      - pyjwt==2.8.0
      - pyparsing==3.0.9
      - python-dotenv==1.0.0
      - pytz==2023.3.post1
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - querystring-parser==1.2.4
      - ray[all]==2.8.0
      - referencing==0.31.0
      - requests==2.31.0
      - rfc3339==6.2
      - rich==13.7.0
      - rpds-py==0.13.1
      - rsa==4.9
      - s3transfer==0.5.2
      - safetensors==0.4.2
      - scikit-image==0.19.3
      - scikit-learn==1.2.1
      - scipy==1.9.3
      - seaborn==0.13.2
      - setuptools==67.0.0
      - shap==0.41.0
      - slicer==0.0.7
      - smart-open==6.2.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==1.4.46
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - tifffile==2023.2.3
      - timm==0.9.12
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - triton==2.1.0
      - typer==0.9.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==1.26.18
      - uvicorn==0.16.0
      - uvloop==0.19.0
      - virtualenv==20.19.0
      - watchfiles==0.21.0
      - watchgod==0.8.2
      - wcwidth==0.2.11
      - webcolors==1.11.1
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.5
      - wrapt==1.16.0
      - yarl==1.9.3